use rh952ncid2v37a3b;

INSERT INTO roles(role_name) VALUES('ROLE_USER');
INSERT INTO roles(role_name) VALUES('ROLE_ADMIN');

INSERT INTO categories(category_name) VALUES('KUDAPAN');
INSERT INTO categories(category_name) VALUES('SAYUR');
INSERT INTO categories(category_name) VALUES('BUMBU');
INSERT INTO categories(category_name) VALUES('MINUMAN');
INSERT INTO categories(category_name) VALUES('DAGING');

INSERT INTO units(unit_name) VALUES('buah');
INSERT INTO units(unit_name) VALUES('kg');
INSERT INTO units(unit_name) VALUES('gr');

INSERT INTO locations(province,city) VALUES('Aceh','Banda Aceh');
INSERT INTO locations(province,city) VALUES('Aceh','Langsa');
INSERT INTO locations(province,city) VALUES('Aceh','Lhokseumawe');
INSERT INTO locations(province,city) VALUES('Aceh','Meulaboh');
INSERT INTO locations(province,city) VALUES('Aceh','Subulussalam');
INSERT INTO locations(province,city) VALUES('Bali','Denpasar');
INSERT INTO locations(province,city) VALUES('Bangka Belitung','Pangkalpinang');
INSERT INTO locations(province,city) VALUES('Banten','Cilegon');
INSERT INTO locations(province,city) VALUES('Banten','Serang');
INSERT INTO locations(province,city) VALUES('Banten','Tangerang Selatan');
INSERT INTO locations(province,city) VALUES('Banten','Tangerang');
INSERT INTO locations(province,city) VALUES('Bengkulu','Bengkulu');
INSERT INTO locations(province,city) VALUES('Gorontalo','Gorontalo');
INSERT INTO locations(province,city) VALUES('Jakarta','Jakarta Barat');
INSERT INTO locations(province,city) VALUES('Jakarta','Jakarta Pusat');
INSERT INTO locations(province,city) VALUES('Jakarta','Jakarta Selatan');
INSERT INTO locations(province,city) VALUES('Jakarta','Jakarta Timur');
INSERT INTO locations(province,city) VALUES('Jakarta','Jakarta Utara');
INSERT INTO locations(province,city) VALUES('Jambi','Sungai Penuh');
INSERT INTO locations(province,city) VALUES('Jambi','Jambi');
INSERT INTO locations(province,city) VALUES('Jawa Barat','Bandung');
INSERT INTO locations(province,city) VALUES('Jawa Barat','Bekasi');
INSERT INTO locations(province,city) VALUES('Jawa Barat','Bogor');
INSERT INTO locations(province,city) VALUES('Jawa Barat','Cimahi');
INSERT INTO locations(province,city) VALUES('Jawa Barat','Cirebon');
INSERT INTO locations(province,city) VALUES('Jawa Barat','Depok');
INSERT INTO locations(province,city) VALUES('Jawa Barat','Sukabumi');
INSERT INTO locations(province,city) VALUES('Jawa Barat','Tasikmalaya');
INSERT INTO locations(province,city) VALUES('Jawa Barat','Banjar');
INSERT INTO locations(province,city) VALUES('Jawa Tengah','Magelang');
INSERT INTO locations(province,city) VALUES('Jawa Tengah','Pekalongan');
INSERT INTO locations(province,city) VALUES('Jawa Tengah','Pruwokerto');
INSERT INTO locations(province,city) VALUES('Jawa Tengah','Salatiga');
INSERT INTO locations(province,city) VALUES('Jawa Tengah','Semarang');
INSERT INTO locations(province,city) VALUES('Jawa Tengah','Surakarta');
INSERT INTO locations(province,city) VALUES('Jawa Tengah','Tegal');
INSERT INTO locations(province,city) VALUES('Jawa Timur','Batu');
INSERT INTO locations(province,city) VALUES('Jawa Timur','Blitar');
INSERT INTO locations(province,city) VALUES('Jawa Timur','Kediri');
INSERT INTO locations(province,city) VALUES('Jawa Timur','Madiun');
INSERT INTO locations(province,city) VALUES('Jawa Timur','Malang');
INSERT INTO locations(province,city) VALUES('Jawa Timur','Mojokerto');
INSERT INTO locations(province,city) VALUES('Jawa Timur','Pasuruan');
INSERT INTO locations(province,city) VALUES('Jawa Timur','Probolinggo');
INSERT INTO locations(province,city) VALUES('Jawa Timur','Surabaya');
INSERT INTO locations(province,city) VALUES('Kalimantan Barat','Pontianak');
INSERT INTO locations(province,city) VALUES('Kalimantan Barat','Singkawang');
INSERT INTO locations(province,city) VALUES('Kalimantan Selatan','Banjarbaru');
INSERT INTO locations(province,city) VALUES('Kalimantan Selatan','Banjarmesin');
INSERT INTO locations(province,city) VALUES('Kalimantan Tengah','Palangkaraya');
INSERT INTO locations(province,city) VALUES('Kalimantan Timur','Balikpapan');
INSERT INTO locations(province,city) VALUES('Kalimantan Timur','Bontang');
INSERT INTO locations(province,city) VALUES('Kalimantan Timur','Samarinda');
INSERT INTO locations(province,city) VALUES('Kalimantan Utara','Tarakan');
INSERT INTO locations(province,city) VALUES('Kepulauan Riau','Batam');
INSERT INTO locations(province,city) VALUES('Kepulauan Riau','Tanjungpinang');
INSERT INTO locations(province,city) VALUES('Lampung','Bandar Lampung');
INSERT INTO locations(province,city) VALUES('Lampung','Metro');
INSERT INTO locations(province,city) VALUES('Maluku Utara','Ternate');
INSERT INTO locations(province,city) VALUES('Maluku Utara','Tidore');
INSERT INTO locations(province,city) VALUES('Maluku','Ambon');
INSERT INTO locations(province,city) VALUES('Maluku','Tual');
INSERT INTO locations(province,city) VALUES('Nusa Tenggara Barat','Bima');
INSERT INTO locations(province,city) VALUES('Nusa Tenggara Barat','Mataram');
INSERT INTO locations(province,city) VALUES('Nusa Tenggara Timur','Kupang');
INSERT INTO locations(province,city) VALUES('Papu Barat','Sorong');
INSERT INTO locations(province,city) VALUES('Papua','Jayapura');
INSERT INTO locations(province,city) VALUES('Riau','Dumai');
INSERT INTO locations(province,city) VALUES('Riau','Pekanbaru');
INSERT INTO locations(province,city) VALUES('Sulawesi Selatan','Makassar');
INSERT INTO locations(province,city) VALUES('Sulawesi Selatan','Palopo');
INSERT INTO locations(province,city) VALUES('Sulawesi Selatan','Parepare');
INSERT INTO locations(province,city) VALUES('Sulawesi Tengah','Palu');
INSERT INTO locations(province,city) VALUES('Sulawesi Tenggara','Bau-bau');
INSERT INTO locations(province,city) VALUES('Sulawesi Tenggara','Kendari');
INSERT INTO locations(province,city) VALUES('Sulawesi Utara','Bitung');
INSERT INTO locations(province,city) VALUES('Sulawesi Utara','Kotamobagu');
INSERT INTO locations(province,city) VALUES('Sulawesi Utara','Manado');
INSERT INTO locations(province,city) VALUES('Sulawesi Utara','Tomohon');
INSERT INTO locations(province,city) VALUES('Sumatra Barat','Bukittinggi');
INSERT INTO locations(province,city) VALUES('Sumatra Barat','Padang');
INSERT INTO locations(province,city) VALUES('Sumatra Barat','Padangpanjang');
INSERT INTO locations(province,city) VALUES('Sumatra Barat','Pariaman');
INSERT INTO locations(province,city) VALUES('Sumatra Barat','Payakumbuh');
INSERT INTO locations(province,city) VALUES('Sumatra Barat','Sawahlunto');
INSERT INTO locations(province,city) VALUES('Sumatra Barat','Solok');
INSERT INTO locations(province,city) VALUES('Sumatra Selatan','LubukLinggau');
INSERT INTO locations(province,city) VALUES('Sumatra Selatan','Pagaralam');
INSERT INTO locations(province,city) VALUES('Sumatra Selatan','Palembang');
INSERT INTO locations(province,city) VALUES('Sumatra Selatan','Prabumulih');
INSERT INTO locations(province,city) VALUES('Sumatra Utara','Binjai');
INSERT INTO locations(province,city) VALUES('Sumatra Utara','Medan');
INSERT INTO locations(province,city) VALUES('Sumatra Utara','Padang Sidempuan');
INSERT INTO locations(province,city) VALUES('Sumatra Utara','Pematangsiantar');
INSERT INTO locations(province,city) VALUES('Sumatra Utara','Sibolga');
INSERT INTO locations(province,city) VALUES('Sumatra Utara','Tanjungbalai');
INSERT INTO locations(province,city) VALUES('Sumatra Utara','Tebingtinggi');
INSERT INTO locations(province,city) VALUES('Yogakarta','Yogakarta');